services:
  spark-job:
    build: .
    container_name: spark-job
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4040:4040"
    stdin_open: true
    tty: true
    command: python src/etl.py